<?php
// $Id$


/**
 * Implementation of hook_menu()
 */
function ejectorseat_menu() {
  $items = array();
  $items['admin/settings/ejectorseat'] = array(
    'title' => 'Ejector Seat settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ejectorseat_settings'),
    'access arguments' => array('administer site configuration')
  );
  $items['ejectorseat/check'] = array(
    'page callback' => 'ejectorseat_check',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implementation of hook_init()
 */
function ejectorseat_init() {
  global $user;
  if ($user->uid > 0 && (int)variable_get('ejectorseat_interval', 60)) {
    drupal_add_js(array(
    'ejectorSeat' => array(
      'interval' => variable_get('ejectorseat_interval', 60),
      'url' => url('ejectorseat/check'),
      'ignoreFocus' => variable_get('ejectorseat_background', 0) ? TRUE : FALSE,
    )), 'setting');
    drupal_add_js(drupal_get_path('module', 'ejectorseat') . '/ejectorseat.js');
  }
}

/**
 * Callback to tell whether user is logged in or not
 */
function ejectorseat_check() {
  global $user;
  print $user->uid == 0 ? 0 : 1;
}

/**
 * Settings form
 */
function ejectorseat_settings() {
  $form = array();
  $period = array(0 => t('disable')) + drupal_map_assoc(array(15, 30, 60, 120, 180, 300, 600, 1200, 1800, 3600), 'format_interval');
  $form['ejectorseat_interval'] = array(
    '#type' => 'select',
    '#title' => t('Ajax check rate'),
    '#options' => $period,
    '#description' => t("How often should the Ejector Seat check to see if a user has been logged out? Lower rates may affect site performance."),
    '#default_value' => variable_get('ejectorseat_interval', 60),
  );
  $form['ejectorseat_background'] = array(
    '#type' => 'radios',
    '#title' => t('Run ajax check in background'),
    '#options' => array(
      0 => t('<strong>FALSE:</strong> Only run the ajax check when the browser window or tab is active. (better performance)'),
      1 => t('<strong>TRUE:</strong> Run the ajax check even if the browser window or tab is in the background. (better security, CONSIDERABLY worse performance)'),
    ),
    '#default_value' => variable_get('ejectorseat_background', 0),
  );
  return system_settings_form($form);
}

